/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    ElButton: (typeof import("element-plus/es"))["ElButton"];
    ElCard: (typeof import("element-plus/es"))["ElCard"];
    ElCol: (typeof import("element-plus/es"))["ElCol"];
    ElDialog: (typeof import("element-plus/es"))["ElDialog"];
    ElDivider: (typeof import("element-plus/es"))["ElDivider"];
    ElDropdown: (typeof import("element-plus/es"))["ElDropdown"];
    ElDropdownItem: (typeof import("element-plus/es"))["ElDropdownItem"];
    ElDropdownMenu: (typeof import("element-plus/es"))["ElDropdownMenu"];
    ElForm: (typeof import("element-plus/es"))["ElForm"];
    ElFormItem: (typeof import("element-plus/es"))["ElFormItem"];
    ElIcon: (typeof import("element-plus/es"))["ElIcon"];
    ElInput: (typeof import("element-plus/es"))["ElInput"];
    ElInputNumber: (typeof import("element-plus/es"))["ElInputNumber"];
    ElLink: (typeof import("element-plus/es"))["ElLink"];
    ElMenu: (typeof import("element-plus/es"))["ElMenu"];
    ElMenuItem: (typeof import("element-plus/es"))["ElMenuItem"];
    ElOption: (typeof import("element-plus/es"))["ElOption"];
    ElPagination: (typeof import("element-plus/es"))["ElPagination"];
    ElPopover: (typeof import("element-plus/es"))["ElPopover"];
    ElRadio: (typeof import("element-plus/es"))["ElRadio"];
    ElRadioGroup: (typeof import("element-plus/es"))["ElRadioGroup"];
    ElRow: (typeof import("element-plus/es"))["ElRow"];
    ElScrollbar: (typeof import("element-plus/es"))["ElScrollbar"];
    ElSelect: (typeof import("element-plus/es"))["ElSelect"];
    ElSubMenu: (typeof import("element-plus/es"))["ElSubMenu"];
    ElSwitch: (typeof import("element-plus/es"))["ElSwitch"];
    ElTable: (typeof import("element-plus/es"))["ElTable"];
    ElTableColumn: (typeof import("element-plus/es"))["ElTableColumn"];
    ElTag: (typeof import("element-plus/es"))["ElTag"];
    ElTooltip: (typeof import("element-plus/es"))["ElTooltip"];
    ElTree: (typeof import("element-plus/es"))["ElTree"];
    ElTreeSelect: (typeof import("element-plus/es"))["ElTreeSelect"];
    ElUpload: (typeof import("element-plus/es"))["ElUpload"];
    GithubCorner: (typeof import("./../components/GithubCorner/index.vue"))["default"];
    Hamburger: (typeof import("./../components/Hamburger/index.vue"))["default"];
    HelloWorld: (typeof import("./../components/HelloWorld.vue"))["default"];
    ICarbonAccessibility: (typeof import("~icons/carbon/accessibility"))["default"];
    IconSelect: (typeof import("./../components/IconSelect/index.vue"))["default"];
    IEpAccessibility: (typeof import("~icons/ep/accessibility"))["default"];
    IEpCaretBottom: (typeof import("~icons/ep/caret-bottom"))["default"];
    IEpCaretTop: (typeof import("~icons/ep/caret-top"))["default"];
    IEpClose: (typeof import("~icons/ep/close"))["default"];
    IEpDelete: (typeof import("~icons/ep/delete"))["default"];
    IEpDownload: (typeof import("~icons/ep/download"))["default"];
    IEpEdit: (typeof import("~icons/ep/edit"))["default"];
    IEpInfoFilled: (typeof import("~icons/ep/info-filled"))["default"];
    IEpPlus: (typeof import("~icons/ep/plus"))["default"];
    IEpPosition: (typeof import("~icons/ep/position"))["default"];
    IEpRefresh: (typeof import("~icons/ep/refresh"))["default"];
    IEpRefreshLeft: (typeof import("~icons/ep/refresh-left"))["default"];
    IEpSearch: (typeof import("~icons/ep/search"))["default"];
    IEpSetting: (typeof import("~icons/ep/setting"))["default"];
    IEpSuccessFilled: (typeof import("~icons/ep/success-filled"))["default"];
    IEpTop: (typeof import("~icons/ep/top"))["default"];
    IEpUploadFilled: (typeof import("~icons/ep/upload-filled"))["default"];
    IEpWarningFilled: (typeof import("~icons/ep/warning-filled"))["default"];
    IEpWarnTriangleFilled: (typeof import("~icons/ep/warn-triangle-filled"))["default"];
    IMakiAnimalShelter: (typeof import("~icons/maki/animal-shelter"))["default"];
    Logo: (typeof import("./../components/Siderbar/Logo.vue"))["default"];
    Pagination: (typeof import("./../components/Pagination/index.vue"))["default"];
    RightPanel: (typeof import("./../components/RightPanel/index.vue"))["default"];
    RouterLink: (typeof import("vue-router"))["RouterLink"];
    RouterView: (typeof import("vue-router"))["RouterView"];
    Siderbar: (typeof import("./../components/Siderbar/index.vue"))["default"];
    SvgIcon: (typeof import("./../components/SvgIcon/index.vue"))["default"];
  }
  export interface ComponentCustomProperties {
    vLoading: (typeof import("element-plus/es"))["ElLoadingDirective"];
  }
}
